// <auto-generated />
namespace EbayWatcher.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addedattributestousers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedattributestousers));
        
        string IMigrationMetadata.Id
        {
            get { return "201408160403015_Added attributes to users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
