// <auto-generated />
namespace EbayWatcher.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addidentityauthentication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addidentityauthentication));
        
        string IMigrationMetadata.Id
        {
            get { return "201408090138413_Add identity authentication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
