//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbayWatcher.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishlistItem
    {
        public WishlistItem()
        {
            this.WishlistItemHistoricalItems = new HashSet<WishlistItemHistoricalItem>();
            this.WishlistItemIgnoreItems = new HashSet<WishlistItemIgnoreItem>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<WishlistItemHistoricalItem> WishlistItemHistoricalItems { get; set; }
        public virtual ICollection<WishlistItemIgnoreItem> WishlistItemIgnoreItems { get; set; }
    }
}
