//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbayWatcher.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishlistItemHistoricalItem
    {
        public int Id { get; set; }
        public int WishlistItemId { get; set; }
        public int EbayId { get; set; }
        public Nullable<decimal> BuyItNowPrice { get; set; }
        public Nullable<decimal> AuctionPrice { get; set; }
        public Nullable<System.DateTime> AuctionEndTime { get; set; }
        public Nullable<int> BidCount { get; set; }
    
        public virtual WishlistItem WishlistItem { get; set; }
    }
}
